########################################################################
# ******** Titel: Password Manager ********
# Version: 1.0
# Autor: Gabriel Franz
# Datum: 05.11.2021
# Beschreibung: Mit dem Skript ist es mÃ¶glich, Benutzernamen und PasswÃ¶rter zu speichern.
# Code generiert von: SAPIEN Technologies PrimalForms (Community Edition) v1.0.10.0
########################################################################

#Generated Form Function
function GenerateForm1 {
########################################################################
# Code Generated By: SAPIEN Technologies PrimalForms (Community Edition) v1.0.10.0
# Generated On: 10/1/2021 11:06 AM
# Generated By: I539356
########################################################################

#region Import the Assemblies
[reflection.assembly]::loadwithpartialname("System.Windows.Forms") | Out-Null
[reflection.assembly]::loadwithpartialname("System.Drawing") | Out-Null
#endregion

#region Generated Form Objects
$Gui1 = New-Object System.Windows.Forms.Form
$Gui1 = New-Object System.Windows.Forms.Form
$Gui1_Box_List = New-Object System.Windows.Forms.ListBox
$Gui1_Btn_Delete = New-Object System.Windows.Forms.Button
$Gui1_Btn_Add = New-Object System.Windows.Forms.Button
$Gui1_Txt_Password_Manager = New-Object System.Windows.Forms.Label
$InitialFormWindowState = New-Object System.Windows.Forms.FormWindowState
#endregion Generated Form Objects

#----------------------------------------------
#Generated Event Script Blocks
#----------------------------------------------
#Provide Custom Code for events specified in PrimalForms.
$Gui1_Btn_Add_Click= 
{

    GenerateForm2 #Gui2 aufrufen / Funktion starten
    $Gui1_Box_List.Items.clear() #Liste löschen
    $CSV = Import-CSV $SavePath #CSV Datei importieren
       
    foreach($Line in $CSV) #Liste neu zusammensetzen
    {
        $Name = "$($Line.NAME)"
        $Gui1_Box_List.Items.Add($Name)
    }

}

$Gui1_Btn_Delete_Click= 
{

    $Name = $Gui1_Box_List.SelectedItem #Ausgewähltes Item in Variable speichern

    $Gui1_Box_List.Items.Remove($Gui1_Box_List.SelectedItem) #Eintrag löschen

    $CSV = Import-Csv $SavePath #CSV Datei importieren

    $DeleteRow = foreach ($Line in $CSV) { #Nach Eintrag in der CSV suchen
        if(-not$($Line.NAME -like $Name)) {
            $Line
        }
    }

    $DeleteRow | Export-Csv $SavePath -NoTypeInformation #Eintrag in CSV löschen

}


$Gui1_Box_List_DoubleClick= 
{

    GenerateForm3 #Funktion aufrufen / Gui3 aufrufen

}


$OnLoadForm_StateCorrection=
{#Correct the initial state of the form to prevent the .Net maximized form issue

    $Gui1.WindowState = $InitialFormWindowState

    $CSV = Import-Csv $SavePath #CSV importieren
    $Gui1_Box_List.Items.clear() #Alle Einträge löschen   
    foreach($Line in $CSV) #Einträge neu auflisten
    {
        $Name = "$($Line.NAME)"
        $Gui1_Box_List.Items.Add($Name)
    }

}

#----------------------------------------------
#region Generated Form Code
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 495
$System_Drawing_Size.Width = 526
$Gui1.ClientSize = $System_Drawing_Size
$Gui1.DataBindings.DefaultDataSourceUpdateMode = 0
$Gui1.Name = "Gui1"
$Gui1.Text = "Passwort Manager"


$Gui1_Box_List.DataBindings.DefaultDataSourceUpdateMode = 0
$Gui1_Box_List.Font = New-Object System.Drawing.Font("Microsoft Sans Serif",14,0,3,1)
$Gui1_Box_List.FormattingEnabled = $True
$Gui1_Box_List.ItemHeight = 24
$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 12
$System_Drawing_Point.Y = 31
$Gui1_Box_List.Location = $System_Drawing_Point
$Gui1_Box_List.Name = "Gui1_Box_List"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 412
$System_Drawing_Size.Width = 502
$Gui1_Box_List.Size = $System_Drawing_Size
$Gui1_Box_List.TabIndex = 4
$Gui1_Box_List.add_DoubleClick($Gui1_Box_List_DoubleClick)

$Gui1.Controls.Add($Gui1_Box_List)


$Gui1_Btn_Delete.DataBindings.DefaultDataSourceUpdateMode = 0

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 288
$System_Drawing_Point.Y = 460
$Gui1_Btn_Delete.Location = $System_Drawing_Point
$Gui1_Btn_Delete.Name = "Gui1_Btn_Delete"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 23
$System_Drawing_Size.Width = 226
$Gui1_Btn_Delete.Size = $System_Drawing_Size
$Gui1_Btn_Delete.TabIndex = 2
$Gui1_Btn_Delete.Text = "Loeschen"
$Gui1_Btn_Delete.UseVisualStyleBackColor = $True
$Gui1_Btn_Delete.add_Click($Gui1_Btn_Delete_Click)

$Gui1.Controls.Add($Gui1_Btn_Delete)


$Gui1_Btn_Add.DataBindings.DefaultDataSourceUpdateMode = 0

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 12
$System_Drawing_Point.Y = 460
$Gui1_Btn_Add.Location = $System_Drawing_Point
$Gui1_Btn_Add.Name = "Gui1_Btn_Add"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 23
$System_Drawing_Size.Width = 244
$Gui1_Btn_Add.Size = $System_Drawing_Size
$Gui1_Btn_Add.TabIndex = 1
$Gui1_Btn_Add.Text = "Hinzufuegen"
$Gui1_Btn_Add.UseVisualStyleBackColor = $True
$Gui1_Btn_Add.add_Click($Gui1_Btn_Add_Click)

$Gui1.Controls.Add($Gui1_Btn_Add)

$Gui1_Txt_Password_Manager.DataBindings.DefaultDataSourceUpdateMode = 0

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 214
$System_Drawing_Point.Y = 9
$Gui1_Txt_Password_Manager.Location = $System_Drawing_Point
$Gui1_Txt_Password_Manager.Name = "Gui1_Txt_Password_Manager"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 23
$System_Drawing_Size.Width = 100
$Gui1_Txt_Password_Manager.Size = $System_Drawing_Size
$Gui1_Txt_Password_Manager.TabIndex = 0
$Gui1_Txt_Password_Manager.Text = "Passwort Manager"

$Gui1.Controls.Add($Gui1_Txt_Password_Manager)

#endregion Generated Form Code

#Save the initial state of the form
$InitialFormWindowState = $Gui1.WindowState
#Init the OnLoad event to correct the initial state of the form
$Gui1.add_Load($OnLoadForm_StateCorrection)
#Show the Form
$Gui1.ShowDialog()| Out-Null

} #End Function


#--------------------------------------------------------------------
#Generated Form Function
function GenerateForm2 {
########################################################################
# Code Generated By: SAPIEN Technologies PrimalForms (Community Edition) v1.0.10.0
# Generated On: 10/1/2021 11:14 AM
# Generated By: I539356
########################################################################

#region Import the Assemblies
[reflection.assembly]::loadwithpartialname("System.Drawing") | Out-Null
[reflection.assembly]::loadwithpartialname("System.Windows.Forms") | Out-Null
#endregion

#region Generated Form Objects
$Gui2 = New-Object System.Windows.Forms.Form
$Gui2_Btn_Cancel = New-Object System.Windows.Forms.Button
$Gui2_Btn_Add = New-Object System.Windows.Forms.Button
$GUI2_Btn_Generate = New-Object System.Windows.Forms.Button
$Gui2_Box_Password = New-Object System.Windows.Forms.TextBox
$Gui2_Txt_Password = New-Object System.Windows.Forms.Label
$Gui2_Box_Username = New-Object System.Windows.Forms.TextBox
$Gui2_Txt_Username = New-Object System.Windows.Forms.Label
$Gui2_Box_Name = New-Object System.Windows.Forms.TextBox
$Gui2_Txt_Name = New-Object System.Windows.Forms.Label
$Gui2_Txt_Entry_Add = New-Object System.Windows.Forms.Label
$InitialFormWindowState = New-Object System.Windows.Forms.FormWindowState
#endregion Generated Form Objects

#----------------------------------------------
#Generated Event Script Blocks
#----------------------------------------------
#Provide Custom Code for events specified in PrimalForms.
$Gui2_Btn_Generate_Click=
{
        $OutputBox = GenerateForm4 #Return in Textbox einfügen

        if ($OutputBox -ne "") { #Überprüfen ob return nicht leer ist
            $Gui2_Box_Password.Text = $OutputBox #Passwort einfügen
            $Gui2_Box_Password.Refresh() #Passwort aktualisieren
        }

}

$Gui2_Btn_Add_Click=
{

    #Read Text from TextBoxes
    $Name = $Gui2_Box_Name.Text #Name von Textbox entnehmen
    $Username = $Gui2_Box_Username.Text #Username von Textbox entnehmen
    $Password = $Gui2_Box_Password.Text #Password von Textbox entnehmen


    if ($Name -ne "" -and $Username -ne "" -and $Password -ne "") {  #ÃœberprÃ¼fen, ob $Name, $Username und $Passwort leer ist

        #Passwort verschlüsseln
        $SecurePwd = $Password | ConvertTo-SecureString -AsPlainText -Force #Passwort zu sicheres Passwort konvertieren
        $EncryptedPwd = $SecurePwd | ConvertFrom-SecureString #Sicheres Passwort verschlüsseln

        $NewRow = New-Object PsObject -Property @{ NAME = $Name ; USERNAME = $Username ; PASSWORD = $EncryptedPwd } #Werte für CSV Zeile
        $NewRow | Export-Csv -Path $SavePath -Force -Append #Neue Zeile mit den oberen Werten erstellen

        $Gui2.close() #GUI 2 schliessen

    } else {

        [System.Windows.MessageBox]::Show('Mindestens ein Eintrag ist leer','Passwort Manager','OK','Error')

    }

}

$Gui2_Btn_Cancel_Click= 
{
    $Gui2.close() #GUI2 schliessen
}

$OnLoadForm_StateCorrection=
{#Correct the initial state of the form to prevent the .Net maximized form issue
    $Gui2.WindowState = $InitialFormWindowState
}

#----------------------------------------------
#region Generated Form Code
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 216
$System_Drawing_Size.Width = 333
$Gui2.ClientSize = $System_Drawing_Size
$Gui2.DataBindings.DefaultDataSourceUpdateMode = 0
$Gui2.Name = "Gui2"
$Gui2.Text = "Eintrag hinzufuegen"


$Gui2_Btn_Cancel.DataBindings.DefaultDataSourceUpdateMode = 0

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 246
$System_Drawing_Point.Y = 181
$Gui2_Btn_Cancel.Location = $System_Drawing_Point
$Gui2_Btn_Cancel.Name = "Gui2_Btn_Cancel"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 23
$System_Drawing_Size.Width = 75
$Gui2_Btn_Cancel.Size = $System_Drawing_Size
$Gui2_Btn_Cancel.TabIndex = 9
$Gui2_Btn_Cancel.Text = "Abbrechen"
$Gui2_Btn_Cancel.UseVisualStyleBackColor = $True
$Gui2_Btn_Cancel.add_Click($Gui2_Btn_Cancel_Click)

$Gui2.Controls.Add($Gui2_Btn_Cancel)


$Gui2_Btn_Add.DataBindings.DefaultDataSourceUpdateMode = 0

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 13
$System_Drawing_Point.Y = 181
$Gui2_Btn_Add.Location = $System_Drawing_Point
$Gui2_Btn_Add.Name = "Gui2_Btn_Add"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 23
$System_Drawing_Size.Width = 80
$Gui2_Btn_Add.Size = $System_Drawing_Size
$Gui2_Btn_Add.TabIndex = 8
$Gui2_Btn_Add.Text = "Hinzufuegen"
$Gui2_Btn_Add.UseVisualStyleBackColor = $True
$Gui2_Btn_Add.add_Click($Gui2_Btn_Add_Click)

$Gui2.Controls.Add($Gui2_Btn_Add)

$Gui2_Btn_Generate.DataBindings.DefaultDataSourceUpdateMode = 0

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 300
$System_Drawing_Point.Y = 151
$Gui2_Btn_Generate.Location = $System_Drawing_Point
$Gui2_Btn_Generate.Name = "Gui2_Btn_Generate"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 23
$System_Drawing_Size.Width = 22
$Gui2_Btn_Generate.Size = $System_Drawing_Size
$Gui2_Btn_Generate.TabIndex = 7
$Gui2_Btn_Generate.Text = "o"
$Gui2_Btn_Generate.UseVisualStyleBackColor = $True
$Gui2_Btn_Generate.add_Click($Gui2_Btn_Generate_Click)

$Gui2.Controls.Add($Gui2_Btn_Generate)

$Gui2_Box_Password.DataBindings.DefaultDataSourceUpdateMode = 0
$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 13
$System_Drawing_Point.Y = 151
$Gui2_Box_Password.Location = $System_Drawing_Point
$Gui2_Box_Password.Name = "Gui2_Box_Password"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 20
$System_Drawing_Size.Width = 280
$Gui2_Box_Password.Size = $System_Drawing_Size
$Gui2_Box_Password.TabIndex = 6

$Gui2.Controls.Add($Gui2_Box_Password)

$Gui2_Txt_Password.DataBindings.DefaultDataSourceUpdateMode = 0

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 12
$System_Drawing_Point.Y = 135
$Gui2_Txt_Password.Location = $System_Drawing_Point
$Gui2_Txt_Password.Name = "Gui2_Txt_Password"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 23
$System_Drawing_Size.Width = 100
$Gui2_Txt_Password.Size = $System_Drawing_Size
$Gui2_Txt_Password.TabIndex = 5
$Gui2_Txt_Password.Text = "Passwort"

$Gui2.Controls.Add($Gui2_Txt_Password)

$Gui2_Box_Username.DataBindings.DefaultDataSourceUpdateMode = 0
$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 12
$System_Drawing_Point.Y = 98
$Gui2_Box_Username.Location = $System_Drawing_Point
$Gui2_Box_Username.Name = "Gui2_Box_Username"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 20
$System_Drawing_Size.Width = 309
$Gui2_Box_Username.Size = $System_Drawing_Size
$Gui2_Box_Username.TabIndex = 4

$Gui2.Controls.Add($Gui2_Box_Username)

$Gui2_Txt_Username.DataBindings.DefaultDataSourceUpdateMode = 0

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 13
$System_Drawing_Point.Y = 85
$Gui2_Txt_Username.Location = $System_Drawing_Point
$Gui2_Txt_Username.Name = "Gui2_Txt_Username"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 23
$System_Drawing_Size.Width = 100
$Gui2_Txt_Username.Size = $System_Drawing_Size
$Gui2_Txt_Username.TabIndex = 3
$Gui2_Txt_Username.Text = "Benutzername"

$Gui2.Controls.Add($Gui2_Txt_Username)

$Gui2_Box_Name.DataBindings.DefaultDataSourceUpdateMode = 0
$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 12
$System_Drawing_Point.Y = 49
$Gui2_Box_Name.Location = $System_Drawing_Point
$Gui2_Box_Name.Name = "Gui2_Box_Name"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 20
$System_Drawing_Size.Width = 309
$Gui2_Box_Name.Size = $System_Drawing_Size
$Gui2_Box_Name.TabIndex = 2

$Gui2.Controls.Add($Gui2_Box_Name)

$Gui2_Txt_Name.DataBindings.DefaultDataSourceUpdateMode = 0

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 13
$System_Drawing_Point.Y = 33
$Gui2_Txt_Name.Location = $System_Drawing_Point
$Gui2_Txt_Name.Name = "Gui2_Txt_Name"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 23
$System_Drawing_Size.Width = 100
$Gui2_Txt_Name.Size = $System_Drawing_Size
$Gui2_Txt_Name.TabIndex = 1
$Gui2_Txt_Name.Text = "Name"

$Gui2.Controls.Add($Gui2_Txt_Name)

$Gui2_Txt_Entry_Add.DataBindings.DefaultDataSourceUpdateMode = 0

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 116
$System_Drawing_Point.Y = 9
$Gui2_Txt_Entry_Add.Location = $System_Drawing_Point
$Gui2_Txt_Entry_Add.Name = "Gui2_Txt_Entry_Add"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 23
$System_Drawing_Size.Width = 110
$Gui2_Txt_Entry_Add.Size = $System_Drawing_Size
$Gui2_Txt_Entry_Add.TabIndex = 0
$Gui2_Txt_Entry_Add.Text = "Eintrag hinzufuegen"

$Gui2.Controls.Add($Gui2_Txt_Entry_Add)

#endregion Generated Form Code

#Save the initial state of the form
$InitialFormWindowState = $Gui2.WindowState
#Init the OnLoad event to correct the initial state of the form
$Gui2.add_Load($OnLoadForm_StateCorrection)
#Show the Form
$Gui2.ShowDialog()| Out-Null

} #End Function


#----------------------------------------------------------------------------------
#Generated Form Function
function GenerateForm3 {
########################################################################
# Code Generated By: SAPIEN Technologies PrimalForms (Community Edition) v1.0.10.0
# Generated On: 10/1/2021 11:07 AM
# Generated By: I539356
########################################################################

#region Import the Assemblies
[reflection.assembly]::loadwithpartialname("System.Drawing") | Out-Null
[reflection.assembly]::loadwithpartialname("System.Windows.Forms") | Out-Null
#endregion

#region Generated Form Objects
$Gui3 = New-Object System.Windows.Forms.Form
$Gui3_Btn_Cancel = New-Object System.Windows.Forms.Button
$Gui3_Btn_Save = New-Object System.Windows.Forms.Button
$Gui3_Box_Password = New-Object System.Windows.Forms.TextBox
$Gui3_Txt_Password = New-Object System.Windows.Forms.Label
$Gui3_Box_Username = New-Object System.Windows.Forms.TextBox
$Gui3_Txt_Username = New-Object System.Windows.Forms.Label
$Gui3_Box_Name = New-Object System.Windows.Forms.TextBox
$Gui3_Txt_Name = New-Object System.Windows.Forms.Label
$InitialFormWindowState = New-Object System.Windows.Forms.FormWindowState
#endregion Generated Form Objects

#----------------------------------------------
#Generated Event Script Blocks
#----------------------------------------------
#Provide Custom Code for events specified in PrimalForms.
$Gui3_Btn_Cancel_Click= 
{

    $Gui3.close() #Gui3 schliessen

}

$Gui3_Btn_Save_Click= 
{

    #Add Entry
    $NewName = $Gui3_Box_Name.Text
    $NewUsername = $Gui3_Box_Username.Text #Neuer Username deklarieren
    $NewPassword = $Gui3_Box_Password.Text #Neues Passwort Deklarieren

    if ($NewName -ne "" -and $NewUsername -ne "" -and $NewPassword -ne "") {  #ÃœberprÃ¼fen, ob $Name, $Username und $Passwort leer ist

        #Detele Row
        $Name = $Gui1_Box_List.SelectedItem #$Name deklarieren

        $Gui1_Box_List.Items.Remove($Gui1_Box_List.SelectedItem) #Select item entfernen

        $CSV = Import-CSV $SavePath #Variable in CSV Importieren

        $DeleteRow = foreach ($Line in $CSV) {
            if(-not$($Line.NAME -like $Name)) {
                $Line
            }
        }

        $DeleteRow | Export-CSV -Path $SavePath -NoTypeInformation #Zeile lÃ¶schen

        #Passwort verschlüsseln
        $SecurePwd = $NewPassword | ConvertTo-SecureString -AsPlainText -Force #Passwort zu sicheres Passwort konvertieren
        $EncryptedPwd = $SecurePwd | ConvertFrom-SecureString #Sicheres Passwort verschlüsseln

        $NewRow = New-Object PsObject -Property @{ NAME = $NewName ; USERNAME = $NewUsername ; PASSWORD = $EncryptedPwd }
        $NewRow | Export-CSV $SavePath -Force -Append

        $CSV = Import-Csv $SavePath #CSV importieren
        $Gui1_Box_List.Items.clear() #Eintrage löschen
        foreach($Line in $CSV) #Einträge neu zusammensetzen
        {
            $Name = "$($Line.NAME)"
            $Gui1_Box_List.Items.Add($Name) #$Name hinzufÃ¼gen
        }

        $Gui3.close() #GUI3 schliessen

     } else {

        [System.Windows.MessageBox]::Show('Mindestens ein Eintrag ist leer','Passwort Manager','OK','Error')

     }
}

$OnLoadForm_StateCorrection=
{#Correct the initial state of the form to prevent the .Net maximized form issue
    $Gui3.WindowState = $InitialFormWindowState

    $Name = $Gui1_Box_List.SelectedItem #$Name von ausgewÃ¤hltem Item deklarieren

    $CSV = Import-Csv $SavePath #Variabel in CSV importieren

    foreach ($Line in $CSV) {

        if ($Line.NAME -eq $Name) { #PrÃ¼fen ob $Line.NAME gleich wie $Name ist
            
            $Name = $Line.NAME #Name auslesen
            $Username = $Line.USERNAME #Username auslesen
            $EncryptedPwd = $Line.PASSWORD #Passwort auslesen
        }
    }


    try { #Befehl unten funktioniert nicht richtig, deswegen einfach Error verbergen
        if ($EncryptedPwd -ne $null -or $EncryptedPwd -ne "") {        
            #Passwort entschlüsseln
            $SecurePwd = $EncryptedPwd | ConvertTo-SecureString -ErrorAction SilentlyContinue #Encrypted Passwort zu Secure Passwort konvertieren
            $Marshal = [System.Runtime.InteropServices.Marshal]
            $Bstr = $Marshal::SecureStringToBSTR($SecurePwd) 
            $Password = $Marshal::PtrToStringAuto($Bstr)
            $Marshal::ZeroFreeBSTR($Bstr) #Arbeitsspeicher bereinigen
        }
    } catch {

    }

    $Gui3_Box_Name.Text = $Name #Name in Textbox einfügen
    $Gui3_Box_Username.Text = $Username #Username in Textbox einfügen
    $Gui3_Box_Password.Text = $Password #Password in Textbox einfügen

}

#----------------------------------------------
#region Generated Form Code
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 243
$System_Drawing_Size.Width = 284
$Gui3.ClientSize = $System_Drawing_Size
$Gui3.DataBindings.DefaultDataSourceUpdateMode = 0
$Gui3.Name = "Gui3"
$Gui3.Text = "Eintrag bearbeiten"


$Gui3_Btn_Cancel.DataBindings.DefaultDataSourceUpdateMode = 0

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 197
$System_Drawing_Point.Y = 201
$Gui3_Btn_Cancel.Location = $System_Drawing_Point
$Gui3_Btn_Cancel.Name = "Gui3_Btn_Cancel"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 23
$System_Drawing_Size.Width = 75
$Gui3_Btn_Cancel.Size = $System_Drawing_Size
$Gui3_Btn_Cancel.TabIndex = 7
$Gui3_Btn_Cancel.Text = "Abbrechen"
$Gui3_Btn_Cancel.UseVisualStyleBackColor = $True
$Gui3_Btn_Cancel.add_Click($Gui3_Btn_Cancel_Click)

$Gui3.Controls.Add($Gui3_Btn_Cancel)


$Gui3_Btn_Save.DataBindings.DefaultDataSourceUpdateMode = 0

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 13
$System_Drawing_Point.Y = 201
$Gui3_Btn_Save.Location = $System_Drawing_Point
$Gui3_Btn_Save.Name = "Gui3_Btn_Save"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 23
$System_Drawing_Size.Width = 75
$Gui3_Btn_Save.Size = $System_Drawing_Size
$Gui3_Btn_Save.TabIndex = 6
$Gui3_Btn_Save.Text = "Speichern"
$Gui3_Btn_Save.UseVisualStyleBackColor = $True
$Gui3_Btn_Save.add_Click($Gui3_Btn_Save_Click)

$Gui3.Controls.Add($Gui3_Btn_Save)

$Gui3_Box_Password.DataBindings.DefaultDataSourceUpdateMode = 0
$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 12
$System_Drawing_Point.Y = 161
$Gui3_Box_Password.Location = $System_Drawing_Point
$Gui3_Box_Password.Name = "Gui3_Box_Password"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 20
$System_Drawing_Size.Width = 260
$Gui3_Box_Password.Size = $System_Drawing_Size
$Gui3_Box_Password.TabIndex = 5

$Gui3.Controls.Add($Gui3_Box_Password)

$Gui3_Txt_Password.DataBindings.DefaultDataSourceUpdateMode = 0

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 93
$System_Drawing_Point.Y = 134
$Gui3_Txt_Password.Location = $System_Drawing_Point
$Gui3_Txt_Password.Name = "Gui3_Txt_Password"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 23
$System_Drawing_Size.Width = 100
$Gui3_Txt_Password.Size = $System_Drawing_Size
$Gui3_Txt_Password.TabIndex = 4
$Gui3_Txt_Password.Text = "Passwort"
$Gui3_Txt_Password.TextAlign = 32

$Gui3.Controls.Add($Gui3_Txt_Password)

$Gui3_Box_Username.DataBindings.DefaultDataSourceUpdateMode = 0
$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 12
$System_Drawing_Point.Y = 98
$Gui3_Box_Username.Location = $System_Drawing_Point
$Gui3_Box_Username.Name = "Gui3_Box_Username"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 20
$System_Drawing_Size.Width = 260
$Gui3_Box_Username.Size = $System_Drawing_Size
$Gui3_Box_Username.TabIndex = 3

$Gui3.Controls.Add($Gui3_Box_Username)

$Gui3_Txt_Username.DataBindings.DefaultDataSourceUpdateMode = 0

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 93
$System_Drawing_Point.Y = 71
$Gui3_Txt_Username.Location = $System_Drawing_Point
$Gui3_Txt_Username.Name = "Gui3_Txt_Username"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 23
$System_Drawing_Size.Width = 100
$Gui3_Txt_Username.Size = $System_Drawing_Size
$Gui3_Txt_Username.TabIndex = 2
$Gui3_Txt_Username.Text = "Benutzername"
$Gui3_Txt_Username.TextAlign = 32

$Gui3.Controls.Add($Gui3_Txt_Username)

$Gui3_Box_Name.DataBindings.DefaultDataSourceUpdateMode = 0
$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 12
$System_Drawing_Point.Y = 35
$Gui3_Box_Name.Location = $System_Drawing_Point
$Gui3_Box_Name.Name = "Gui3_Box_Name"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 20
$System_Drawing_Size.Width = 260
$Gui3_Box_Name.Size = $System_Drawing_Size
$Gui3_Box_Name.TabIndex = 1

$Gui3.Controls.Add($Gui3_Box_Name)

$Gui3_Txt_Name.DataBindings.DefaultDataSourceUpdateMode = 0

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 93
$System_Drawing_Point.Y = 9
$Gui3_Txt_Name.Location = $System_Drawing_Point
$Gui3_Txt_Name.Name = "Gui3_Txt_Name"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 23
$System_Drawing_Size.Width = 100
$Gui3_Txt_Name.Size = $System_Drawing_Size
$Gui3_Txt_Name.TabIndex = 0
$Gui3_Txt_Name.Text = "Name"
$Gui3_Txt_Name.TextAlign = 32

$Gui3.Controls.Add($Gui3_Txt_Name)

#endregion Generated Form Code

#Save the initial state of the form
$InitialFormWindowState = $Gui3.WindowState
#Init the OnLoad event to correct the initial state of the form
$Gui3.add_Load($OnLoadForm_StateCorrection)
#Show the Form
$Gui3.ShowDialog()| Out-Null

} #End Function


#Generated Form Function
function GenerateForm4 {

    #region Import the Assemblies
    [reflection.assembly]::loadwithpartialname("System.Drawing") | Out-Null
    [reflection.assembly]::loadwithpartialname("System.Windows.Forms") | Out-Null
    #endregion

    #region Generated Form Objects
    $Gui4 = New-Object System.Windows.Forms.Form
    $Gui4_CBox_Symbol = New-Object System.Windows.Forms.CheckBox
    $Gui4_CBox_Number = New-Object System.Windows.Forms.CheckBox
    $Gui4_CBox_Lower = New-Object System.Windows.Forms.CheckBox
    $Gui4_CBox_Upper = New-Object System.Windows.Forms.CheckBox
    $Gui4_Box_Output = New-Object System.Windows.Forms.TextBox
    $Gui4_Txt_Max = New-Object System.Windows.Forms.Label
    $Gui4_Txt_Min = New-Object System.Windows.Forms.Label
    $Gui4_Ud_Max = New-Object System.Windows.Forms.NumericUpDown
    $Gui4_Ud_Min = New-Object System.Windows.Forms.NumericUpDown
    $Gui4_Btn_Generate = New-Object System.Windows.Forms.Button
    $Gui4_Btn_Save = New-Object System.Windows.Forms.Button
    $Gui4_Title = New-Object System.Windows.Forms.Label
    $InitialFormWindowState = New-Object System.Windows.Forms.FormWindowState
    #endregion Generated Form Objects

    #----------------------------------------------
    #Generated Event Script Blocks
    #----------------------------------------------
    #Provide Custom Code for events specified in PrimalForms.
    $Gui4_Btn_Generate_Click=
    {
        #Werte initialisieren!
        $Min = [int]$Gui4_Ud_Min.Value
        $Max = [int]$Gui4_Ud_Max.Value + 1
        $Error = $False

        #Listen mit Grossbuchstaben, Kleinbuchstaben, Zahlen und Symbolen erstellen
        $Upper = "ABCDEFGHIJKLMNOPQRSTUVWXYZ".ToCharArray() #ToCharArray um alle Zeichen einzeln in eine Liste zu packen
        $Lower = "abcdefghijklmnopqrstuvwxyz".ToCharArray()
        $Number = "0123456789".ToCharArray()
        $Symbol = "+-.,;:()/_$%&*#@".ToCharArray()

        #Neue Passwortausgabeliste erstellen
        $PasswordPrint = New-Object System.Collections.ArrayList


        #Wenn checkbox aktiviert, Grossbuchstaben zur Zeichenliste hinzufÃ¼gen
        if ($Gui4_CBox_Upper.Checked) {
            $CharArray += $Upper
        }

        #Wenn checkbox aktiviert, Kleinbuchstaben zur Zeichenliste hinzufÃ¼gen
        if ($Gui4_CBox_Lower.Checked) {
            $CharArray += $Lower
        }

        #Wenn checkbox aktiviert, Zahlen zur Zeichenliste hinzufÃ¼gen
        if ($Gui4_CBox_Number.Checked) {
            $CharArray += $Number
        }

        #Wenn checkbox aktiviert, Symbole zur Zeichenliste hinzufÃ¼gen
        if ($Gui4_CBox_Symbol.Checked) {
            $CharArray += $Symbol
        }

        #ÃœberprÃ¼fen ob mindestens eine Checkbox aktiviert ist
        if ($Gui4_CBox_Upper.Checked -eq $False -and $Gui4_CBox_Lower.Checked -eq $False -and $Gui4_CBox_Number.Checked -eq $False -and $Gui4_CBox_Symbol.Checked -eq $False) {
            $Error = $True
            [System.Windows.MessageBox]::Show('You have to at least tick one box!','Passwort Manager','OK','Error')
        }

        #ÃœberprÃ¼fen ob Minimalwert grÃ¶sser ist als Maximalwert (Sollte nicht mÃ¶glich sein)
        if ($Min -gt $Max) {
            $Error = $True
            [System.Windows.MessageBox]::Show('The minimum value must be lower than the maximum value!','Passwort Manager','OK','Error')
        }

        #ÃœberprÃ¼fen ob Anzahl-, Minimal- oder Maximalwert gleich 0 ist
        if ($Min -eq 0 -or $Max -eq 0) {
            $Error = $True
            [System.Windows.MessageBox]::Show('The minimum or maximum value cant be zero!','Passwort Manager','OK','Error')
        }

        if ($Error -eq $False) { #ÃœberprÃ¼fen ob es keinen Error gab
            $Length = Get-Random -Minimum $Min -Maximum $Max #ZufÃ¤llige LÃ¤nge aus dem Minimal und Maximal Wert generieren
            $Password = ($CharArray | Get-Random -Count $Length) -join '' #Passwort aus der Zeichenliste und der LÃ¤nge generieren
            $Password = "$Password"

            $PasswordPrint.Add($Password) | Out-Null #Passwort zur Passwortausgabeliste hinzufÃ¼gen

            $Gui4_Box_Output.Text = $PasswordPrint #Passwortprintliste ausgeben
        }
        #System.Runtime.InteropServices.ExternalException,Microsoft.PowerShell.Commands.SetClipboardCommand verhindern bei zu schnellem klicken auf den Generate Password Knopf
        Start-Sleep -Milliseconds 500
    }

    $Gui4_Btn_Save_Click=
    {

        $Gui4.hide() #Gui4 verstecken

    }


    $OnLoadForm_StateCorrection=
    {#Correct the initial state of the form to prevent the .Net maximized form issue
        $Gui4.WindowState = $InitialFormWindowState
    }

    #----------------------------------------------
    #region Generated Form Code
    $System_Drawing_Size = New-Object System.Drawing.Size
    $System_Drawing_Size.Height = 335
    $System_Drawing_Size.Width = 480
    $Gui4.ClientSize = $System_Drawing_Size
    $Gui4.DataBindings.DefaultDataSourceUpdateMode = 0
    $Gui4.Name = "Gui4"
    $Gui4.Text = "Passwort Generator"


    $Gui4_CBox_Symbol.DataBindings.DefaultDataSourceUpdateMode = 0

    $System_Drawing_Point = New-Object System.Drawing.Point
    $System_Drawing_Point.X = 13
    $System_Drawing_Point.Y = 206
    $Gui4_CBox_Symbol.Location = $System_Drawing_Point
    $Gui4_CBox_Symbol.Name = "Gui4_CBox_Symbol"
    $System_Drawing_Size = New-Object System.Drawing.Size
    $System_Drawing_Size.Height = 24
    $System_Drawing_Size.Width = 104
    $Gui4_CBox_Symbol.Size = $System_Drawing_Size
    $Gui4_CBox_Symbol.TabIndex = 11
    $Gui4_CBox_Symbol.Text = "Symbole"
    $Gui4_CBox_Symbol.UseVisualStyleBackColor = $True

    $Gui4.Controls.Add($Gui4_CBox_Symbol)


    $Gui4_CBox_Number.DataBindings.DefaultDataSourceUpdateMode = 0

    $System_Drawing_Point = New-Object System.Drawing.Point
    $System_Drawing_Point.X = 12
    $System_Drawing_Point.Y = 175
    $Gui4_CBox_Number.Location = $System_Drawing_Point
    $Gui4_CBox_Number.Name = "Gui4_CBox_Number"
    $System_Drawing_Size = New-Object System.Drawing.Size
    $System_Drawing_Size.Height = 24
    $System_Drawing_Size.Width = 104
    $Gui4_CBox_Number.Size = $System_Drawing_Size
    $Gui4_CBox_Number.TabIndex = 10
    $Gui4_CBox_Number.Text = "Nummern"
    $Gui4_CBox_Number.UseVisualStyleBackColor = $True
    $Gui4_CBox_Number.Checked = $True #Standartwert setzen

    $Gui4.Controls.Add($Gui4_CBox_Number)


    $Gui4_CBox_Lower.DataBindings.DefaultDataSourceUpdateMode = 0

    $System_Drawing_Point = New-Object System.Drawing.Point
    $System_Drawing_Point.X = 12
    $System_Drawing_Point.Y = 144
    $Gui4_CBox_Lower.Location = $System_Drawing_Point
    $Gui4_CBox_Lower.Name = "Gui4_Btn_Lower"
    $System_Drawing_Size = New-Object System.Drawing.Size
    $System_Drawing_Size.Height = 24
    $System_Drawing_Size.Width = 120
    $Gui4_CBox_Lower.Size = $System_Drawing_Size
    $Gui4_CBox_Lower.TabIndex = 9
    $Gui4_CBox_Lower.Text = "Kleinbuchstaben"
    $Gui4_CBox_Lower.UseVisualStyleBackColor = $True
    $Gui4_CBox_Lower.Checked = $True #Standartwert setzen

    $Gui4.Controls.Add($Gui4_CBox_Lower)


    $Gui4_CBox_Upper.DataBindings.DefaultDataSourceUpdateMode = 0

    $System_Drawing_Point = New-Object System.Drawing.Point
    $System_Drawing_Point.X = 13
    $System_Drawing_Point.Y = 113
    $Gui4_CBox_Upper.Location = $System_Drawing_Point
    $Gui4_CBox_Upper.Name = "Gui4_CBox_Upper"
    $System_Drawing_Size = New-Object System.Drawing.Size
    $System_Drawing_Size.Height = 24
    $System_Drawing_Size.Width = 120
    $Gui4_CBox_Upper.Size = $System_Drawing_Size
    $Gui4_CBox_Upper.TabIndex = 8
    $Gui4_CBox_Upper.Text = "Grossbuchstaben"
    $Gui4_CBox_Upper.UseVisualStyleBackColor = $True
    $Gui4_CBox_Upper.Checked = $True #Standartwert setzen

    $Gui4.Controls.Add($Gui4_CBox_Upper)

    $Gui4_Box_Output.DataBindings.DefaultDataSourceUpdateMode = 0
    $Gui4_Box_Output.Font = New-Object System.Drawing.Font("Microsoft Sans Serif",14,0,3,1)
    $System_Drawing_Point = New-Object System.Drawing.Point
    $System_Drawing_Point.X = 170
    $System_Drawing_Point.Y = 39
    $Gui4_Box_Output.Location = $System_Drawing_Point
    $Gui4_Box_Output.Multiline = $False
    $Gui4_Box_Output.Name = "Gui4_Box_Output"
    $System_Drawing_Size = New-Object System.Drawing.Size
    $System_Drawing_Size.Height = 241
    $System_Drawing_Size.Width = 298
    $Gui4_Box_Output.Size = $System_Drawing_Size
    $Gui4_Box_Output.TabIndex = 7
    $Gui4_Box_Output.TextAlign = 2

    $Gui4.Controls.Add($Gui4_Box_Output)

    $Gui4_Txt_Max.DataBindings.DefaultDataSourceUpdateMode = 0

    $System_Drawing_Point = New-Object System.Drawing.Point
    $System_Drawing_Point.X = 60
    $System_Drawing_Point.Y = 68
    $Gui4_Txt_Max.Location = $System_Drawing_Point
    $Gui4_Txt_Max.Name = "Gui4_Txt_Max"
    $System_Drawing_Size = New-Object System.Drawing.Size
    $System_Drawing_Size.Height = 19
    $System_Drawing_Size.Width = 191
    $Gui4_Txt_Max.Size = $System_Drawing_Size
    $Gui4_Txt_Max.TabIndex = 6
    $Gui4_Txt_Max.Text = "Maximale Länge"
    $Gui4_Txt_Max.TextAlign = 16

    $Gui4.Controls.Add($Gui4_Txt_Max)

    $Gui4_Txt_Min.DataBindings.DefaultDataSourceUpdateMode = 0

    $System_Drawing_Point = New-Object System.Drawing.Point
    $System_Drawing_Point.X = 60
    $System_Drawing_Point.Y = 41
    $Gui4_Txt_Min.Location = $System_Drawing_Point
    $Gui4_Txt_Min.Name = "Gui4_Txt_Min"
    $System_Drawing_Size = New-Object System.Drawing.Size
    $System_Drawing_Size.Height = 19
    $System_Drawing_Size.Width = 182
    $Gui4_Txt_Min.Size = $System_Drawing_Size
    $Gui4_Txt_Min.TabIndex = 5
    $Gui4_Txt_Min.Text = "Minimale Länge"
    $Gui4_Txt_Min.TextAlign = 16

    $Gui4.Controls.Add($Gui4_Txt_Min)

    $Gui4_Ud_Max.DataBindings.DefaultDataSourceUpdateMode = 0
    $System_Drawing_Point = New-Object System.Drawing.Point
    $System_Drawing_Point.X = 12
    $System_Drawing_Point.Y = 68
    $Gui4_Ud_Max.Location = $System_Drawing_Point
    $Gui4_Ud_Max.Name = "Gui4_Ud_Max"
    $System_Drawing_Size = New-Object System.Drawing.Size
    $System_Drawing_Size.Height = 20
    $System_Drawing_Size.Width = 41
    $Gui4_Ud_Max.Size = $System_Drawing_Size
    $Gui4_Ud_Max.TabIndex = 4
    $Gui4_Ud_Max.Value = 8 #Standartwert setzen

    $Gui4.Controls.Add($Gui4_Ud_Max)

    $Gui4_Ud_Min.DataBindings.DefaultDataSourceUpdateMode = 0
    $System_Drawing_Point = New-Object System.Drawing.Point
    $System_Drawing_Point.X = 12
    $System_Drawing_Point.Y = 41
    $Gui4_Ud_Min.Location = $System_Drawing_Point
    $Gui4_Ud_Min.Name = "Gui4_Ud_Min"
    $System_Drawing_Size = New-Object System.Drawing.Size
    $System_Drawing_Size.Height = 20
    $System_Drawing_Size.Width = 41
    $Gui4_Ud_Min.Size = $System_Drawing_Size
    $Gui4_Ud_Min.TabIndex = 3
    $Gui4_Ud_Min.Value = 4 #Standartwert setzen

    $Gui4.Controls.Add($Gui4_Ud_Min)


    $Gui4_Btn_Generate.DataBindings.DefaultDataSourceUpdateMode = 0

    $System_Drawing_Point = New-Object System.Drawing.Point
    $System_Drawing_Point.X = 12
    $System_Drawing_Point.Y = 301
    $Gui4_Btn_Generate.Location = $System_Drawing_Point
    $Gui4_Btn_Generate.Name = "Gui4_Btn_Generate"
    $System_Drawing_Size = New-Object System.Drawing.Size
    $System_Drawing_Size.Height = 23
    $System_Drawing_Size.Width = 200
    $Gui4_Btn_Generate.Size = $System_Drawing_Size
    $Gui4_Btn_Generate.TabIndex = 2
    $Gui4_Btn_Generate.Text = "Generieren"
    $Gui4_Btn_Generate.UseVisualStyleBackColor = $True
    $Gui4_Btn_Generate.add_Click($Gui4_Btn_Generate_Click)

    $Gui4.Controls.Add($Gui4_Btn_Generate)

    $Gui4_Btn_Generate.DataBindings.DefaultDataSourceUpdateMode = 0

    $System_Drawing_Point = New-Object System.Drawing.Point
    $System_Drawing_Point.X = 250
    $System_Drawing_Point.Y = 301
    $Gui4_Btn_Save.Location = $System_Drawing_Point
    $Gui4_Btn_Save.Name = "Gui4_Btn_Save"
    $System_Drawing_Size = New-Object System.Drawing.Size
    $System_Drawing_Size.Height = 23
    $System_Drawing_Size.Width = 200
    $Gui4_Btn_Save.Size = $System_Drawing_Size
    $Gui4_Btn_Save.TabIndex = 1
    $Gui4_Btn_Save.Text = "Speichern"
    $Gui4_Btn_Save.UseVisualStyleBackColor = $True
    $Gui4_Btn_Save.add_Click($Gui4_Btn_Save_Click)

    $Gui4.Controls.Add($Gui4_Btn_Save)

    $Gui4_Title.DataBindings.DefaultDataSourceUpdateMode = 0

    $System_Drawing_Point = New-Object System.Drawing.Point
    $System_Drawing_Point.X = 190
    $System_Drawing_Point.Y = 13
    $Gui4_Title.Location = $System_Drawing_Point
    $Gui4_Title.Name = "Gui4_Title"
    $System_Drawing_Size = New-Object System.Drawing.Size
    $System_Drawing_Size.Height = 23
    $System_Drawing_Size.Width = 455
    $Gui4_Title.Size = $System_Drawing_Size
    $Gui4_Title.TabIndex = 0
    $Gui4_Title.Text = "Passwort Generator"
    $Gui4_Title.TextAlign = 16

    $Gui4.Controls.Add($Gui4_Title)

    #endregion Generated Form Code

    #Save the initial state of the form
    $InitialFormWindowState = $Gui4.WindowState
    #Init the OnLoad event to correct the initial state of the form
    $Gui4.add_Load($OnLoadForm_StateCorrection)
    #Show the Form
    $Gui4.ShowDialog()| Out-Null
    return $Gui4_Box_Output.Text
    $Gui4.close()


} #End Function

#--------------------------------------------------
#Code bevor das Program startet
#Globale Variablen
$Path = "$env:APPDATA\" #Pfad deklarieren
$FolderName = "Passwort Manager" #Foldername deklarieren
$FileName = "Passwords" #Filename Deklarieren
$Ext = ".csv" #Extention deklarieren
$SavePath = "$Path$FolderName\$FileName$ext" #Speicherpfad deklarieren

$TestPath = Test-Path -Path ($Path+$FolderName)
$TestFile = Test-Path -Path ($SavePath)

if ($TestPath -eq $False) { #ÃœberprÃ¼fen, ob Ordner in Pfad noch nicht vorhanden ist

    [void](New-Item -itemType Directory -Path $Path -Name $FolderName) #Neuer Ordner erstellen

}

if ($TestFile -eq $False) { #ÃœberprÃ¼fen, ob CSV Datei noch nicht vorhanden ist
    
    $NewCSV = {} | Select "NAME","USERNAME","PASSWORD" | Export-Csv $SavePath -Encoding ASCII -NoTypeInformation #Neues CSV erstellen
    [void][System.Windows.MessageBox]::Show("CSV Datei erstellt unter "+ $SavePath,'Passwort Manager','OK','Info')

}

#Call the Function
GenerateForm1

